const CartActionTypes = {
  HANDLE_CART_TOTAL: "HANDLE_CART_TOTAL",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  ADD_TO_CART: "ADD_TO_CART",
  HANDLE_QUANTITY: "HANDLE_QUANTITY"
};

export default CartActionTypes;
